### PR TITLE
Issue 4 workaround

### PR DESCRIPTION
**Pull request by brad-anton**
This is a workaround for issue 4 (https://github.com/moxie0/chapcrack/issues/4)

### CODE REVIEW

**Comment by moxie0** [comment]
Thanks for this!  Sorry for the nits, but can we:

1) Remove the comment
2) Call it checkKeyPartial
3) Rename the arguments from pt, ct, plain, and cipher to plaintext and ciphertext
4) Rename b to b1
5) Rename guess to b2
6) Remove the commented out code
7) Fix the indentation on the pool.map call

**Comment by moxie0** [comment]
...and also, squash all this into one commit?

**Comment by brad-anton** [comment]
Ya - I knew I should have removed that comment :) will take care of everything on Sunday

**Comment by moxie0** [comment]
Is it possible to get a single squashed commit as a pull request for fixing the partial() issue?

**Comment by moxie0** [comment]
Just went ahead and made this changes myself.

**Comment by brad-anton** [comment]
Wowza's! Looks like you were busy tonight! Sorry I wasn't able to get to
everything- work pulled me into the void!

On Aug 14, 2012, at 8:57 PM, Moxie Marlinspike notifications@github.com
wrote:

Just went ahead and made this changes myself.

—
Reply to this email directly or view it on
GitHubhttps://github.com/moxie0/chapcrack/pull/6#issuecomment-7745311.

**Pull request closed without merging**
